// ============================================================================
// Print Queue export worker — does the heavy lifting (gcode concatenation,
// JSZip generation, DEFLATE compression) off the main thread so the UI stays
// responsive on multi-GB farm-loop archives.
//
// Wire protocol:
//   main → worker: { type: 'build', jobs, loops, endGcode, cooldown, baseBuffer }
//   main → worker: { type: 'ack' }                       (backpressure)
//   worker → main: { type: 'progress', message }
//   worker → main: { type: 'chunk', chunk, percent }     (transferable buffer)
//   worker → main: { type: 'done' }
//   worker → main: { type: 'error', message }
// ============================================================================

importScripts('https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js');

// Must mirror constants in printQueue.js
// Cali section bounds: starts at the "extrude cali test" header and ends at
// the next major section header — "turn off light and wait extrude temperature".
// Both anchored at line start so they don't match the same text appearing
// inside the `; machine_start_gcode = ...` config comment.
const EXTRUDE_CALI_START_RE = /^M620.3 W1; === turn on filament tangle detection=+/m;
const EXTRUDE_CALI_END_RE = /^;========turn off light and wait extrude temperature =+/m;

const EXTRUDE_CALI_REPLACEMENT = `
M620.3 W1; === turn on filament tangle detection===

M400 S2


G90
M83
G0 E50 F100
M400
M400
`;

// Wipe-nozzle section: starts at `;===== wipe nozzle =====...` and ends at
// `M211 R[; pop softend status]`. The end marker is preserved in the output.
const WIPE_NOZZLE_START_RE = /^;===== wipe nozzle =+/m;
const WIPE_NOZZLE_END_RE = /^G1 X25 Y175 F30000.1 ;Brush material+/m;
const WIPE_NOZZLE_REPLACEMENT = `
;===== wipe nozzle ===============================
M1002 gcode_claim_action : 14
M975 S1

M104 S170 ; set temp down to heatbed acceptable
M106 S255 ; turn on fan (G28 has turn off fan)
M211 S; push soft endstop status
M211 X0 Y0 Z0 ;turn off Z axis endstop

M83
G1 E-1 F500
G90
M83

M109 S170
M104 S140
G0 X90 Y-4 F30000
G90
G1 Z5 F30000
G1 X25 Y175 F30000.1 ; Brush material
G1 Z0.2 F30000.1
G1 Y185
G91
G1 X-30 F30000
G1 Y-2
G1 X27
G1 Y1.5
G1 X-28
G1 Y-2
G1 X30
G1 Y1.5
G1 X-30
G90
M83
G1 Z5
G0 X55 Y175 F20000 ; find a soft place to home
G28 Z P0 T300 ; home z with low precision, permit 300deg temperature
G29.2 S0 ; turn off ABL
G1 Z10
G1 X85 Y185
G1 Z-1.01
G1 X95
G1 X90
M211 R ; pop softend status

G1 Z5 F30000
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
`;

// Re-enable runout / clog / tangle detection just before the soft-endstop
// disable in the post-cali block (after the "turn off light" section).
const SOFT_ENDSTOP_OFF_RE = /^M211 X0 Y0 Z0\b/m;
const PRE_SOFT_ENDSTOP_INJECTION = `M412 S1 ;    ===turn on  filament runout detection===
M400 P10

G392 S0 ;turn on clog detect

M620.3 W1; === turn on filament tangle detection===
M400 S2

`;

const PRINT_END_TRIGGER = /^M17 R[^\n]*\n/m;

// Backpressure: each chunk emitted waits for the main thread to acknowledge
// it has been written to disk before the JSZip stream resumes. Without this,
// chunks pile up in the postMessage queue on big files.
let resumeNext = null;

self.onmessage = (ev) => {
  const msg = ev.data;
  if (msg.type === 'ack') {
    if (resumeNext) {
      const fn = resumeNext;
      resumeNext = null;
      fn();
    }
    return;
  }
  if (msg.type === 'build') {
    handleBuild(msg).catch(err => {
      self.postMessage({ type: 'error', message: err && err.message ? err.message : String(err) });
    });
  }
};

async function handleBuild({ jobs, loops, endGcode, cooldown, baseBuffer, preEndMin, preEndCode }) {
  self.postMessage({ type: 'progress', message: 'Reading base archive...' });

  const baseZip = await JSZip.loadAsync(baseBuffer);
  const filenames = Object.keys(baseZip.files);

  const targetGcodePath = filenames.find(f =>
    f.toLowerCase().endsWith('.gcode') && !f.toLowerCase().endsWith('.md5')
  ) || 'Metadata/plate_1.gcode';

  const ejection = trimAllLines(endGcode.endsWith('\n') ? endGcode : endGcode + '\n');
  const ejectionMarker = '\n; ==== farm-loop ejection ====\n';

  self.postMessage({ type: 'progress', message: 'Concatenating G-code...' });

  // Aggregate totals for header + slice_info update
  let totalTime = 0;
  let totalWeight = 0;
  let timeKnown = true;
  let weightKnown = true;
  for (const j of jobs) {
    if (j.timeSeconds != null) totalTime += j.timeSeconds; else timeKnown = false;
    if (j.weightG != null) totalWeight += j.weightG; else weightKnown = false;
  }
  totalTime *= loops;
  totalWeight *= loops;
  const cooldownTotal = (cooldown || 0) * loops;
  if (timeKnown) totalTime += cooldownTotal;

  const chunks = [];
  chunks.push(`; Generated by Print Queue — farm-loop concatenation\n`);
  chunks.push(`; jobs: ${jobs.length}, loops: ${loops}, total prints: ${jobs.length * loops}\n`);
  if (cooldown > 0) {
    chunks.push(`; cooldown after each loop: ${cooldown}s (×${loops} = ${cooldownTotal}s)\n`);
  }
  if (timeKnown) chunks.push(`; total estimated time: ${formatSeconds(totalTime)} (${totalTime}s)\n`);
  if (weightKnown) chunks.push(`; total filament weight [g]: ${totalWeight.toFixed(2)}\n`);
  chunks.push(`;\n`);

  const totalPrints = loops * jobs.length;
  let printSeq = 0;

  for (let loop = 0; loop < loops; loop++) {
    for (let i = 0; i < jobs.length; i++) {
      const job = jobs[i];
      printSeq++;
      const isVeryLast = printSeq === totalPrints;

      let content = replaceExtrudeCaliSection(job.gcodeContent, EXTRUDE_CALI_REPLACEMENT);
      content = replaceWipeNozzleSection(content, WIPE_NOZZLE_REPLACEMENT);
      content = injectBeforeSoftEndstop(content, PRE_SOFT_ENDSTOP_INJECTION);
      if (preEndCode && preEndMin > 0) {
        content = injectBeforeEnd(content, preEndMin, preEndCode, {
          jobName: job.name,
          loopIdx: loop + 1,
          totalLoops: loops,
          printIdx: i + 1,
          totalPrints: jobs.length,
        });
      }

      // Split into print body (up to & including `M17 R ; restore z current`)
      // and original end-of-print (cooldown, park, finish sound, motors off).
      // Order in the output: body → custom ejection → original end.
      const { body, end: originalEnd } = splitAtPrintEnd(content);
      const trimmedBody = trimAllLines(body);
      // Bambu's "park" move at the start of the end-of-print stays at the
      // current Z. For farm-loop printing we want to clear the bed (Z20) so
      // the ejection has headroom before the printer parks.
      let fixedEnd = originalEnd.replace(
        /^G1 X-13 Y180 F3600$/m,
        'G1 X-13 Y180 Z20 F3600'
      );
      // Final motor-off: replace the LAST `M18 X Y Z` with a plain `M18`
      // so every stepper (incl. extruder) is fully disabled, not just XYZ.
      fixedEnd = replaceLastM18XYZ(fixedEnd);
      const trimmedEnd = trimAllLines(fixedEnd);

      chunks.push(`\n; ==== loop ${loop + 1}/${loops} — print ${i + 1}/${jobs.length}: ${job.name} ====\n`);
      chunks.push(trimmedBody);
      if (!trimmedBody.endsWith('\n')) chunks.push('\n');
      chunks.push(ejectionMarker);
      chunks.push(ejection);
      if (trimmedEnd) {
        chunks.push('\n; ==== original end-of-print ====\n');
        chunks.push(trimmedEnd);
        if (!trimmedEnd.endsWith('\n')) chunks.push('\n');
      }

      // Between-prints separator (not after the very last print).
      if (!isVeryLast) {
        chunks.push(`\n; === END OF LOOP ${printSeq} ===\n`);
        chunks.push(`; Preparing for next loop...\n`);
        chunks.push(`G4 S2 ; brief pause between loops\n`);
      }
    }
  }

  const concatenated = new Blob(chunks, { type: 'text/plain;charset=utf-8' });
  baseZip.file(targetGcodePath, concatenated);

  const md5Path = targetGcodePath + '.md5';
  if (baseZip.files[md5Path]) baseZip.remove(md5Path);

  // Update slice_info.config so the printer shows the correct prediction
  const sliceInfoPath = filenames.find(f => f.toLowerCase().includes('slice_info.config'));
  if (sliceInfoPath) {
    try {
      let xml = await baseZip.files[sliceInfoPath].async('text');
      if (timeKnown) xml = replaceMetadataValue(xml, 'prediction', String(Math.round(totalTime)));
      if (weightKnown) xml = replaceMetadataValue(xml, 'weight', totalWeight.toFixed(2));
      baseZip.file(sliceInfoPath, xml);
    } catch (e) {
      // Non-fatal: keep going
    }
  }

  self.postMessage({ type: 'progress', message: 'Compressing & writing...' });

  // Stream the ZIP back as Uint8Array chunks (transferable).
  await new Promise((resolve, reject) => {
    const stream = baseZip.generateInternalStream({
      type: 'uint8array',
      compression: 'DEFLATE',
      streamFiles: true,
    });
    stream.on('data', (chunk, metadata) => {
      stream.pause();
      const percent = metadata && typeof metadata.percent === 'number' ? metadata.percent : 0;
      // IMPORTANT: pako (JSZip's DEFLATE engine) reuses one internal ArrayBuffer
      // across chunks, exposing each chunk as a different Uint8Array view onto it.
      // If we transfer chunk.buffer, the next chunk pako emits points to a
      // detached buffer → "Cannot perform Construct on a detached ArrayBuffer".
      // Copy into a fresh buffer before transferring.
      const copy = new Uint8Array(chunk);
      self.postMessage(
        { type: 'chunk', chunk: copy, percent },
        [copy.buffer]
      );
      resumeNext = () => stream.resume();
    });
    stream.on('error', err => reject(err));
    stream.on('end', () => resolve());
    stream.resume();
  });

  self.postMessage({ type: 'done' });
}

// ── Transformations ────────────────────────────────────────────────────────
// Insert the runout / clog / tangle detection re-enable block right before
// the soft-endstop disable line that sits AFTER the "turn off light and
// wait extrude temperature" section. Bambu gcode has several `M211 X0 Y0 Z0`
// lines in the start sequence — we specifically want the one in the
// post-cali block, so the search is anchored AFTER the turn-off-light header.
function injectBeforeSoftEndstop(gcode, snippet) {
  const turnOffLightRe = /^;========turn off light and wait extrude temperature =+/m;
  const turnOffMatch = gcode.match(turnOffLightRe);
  if (!turnOffMatch) return gcode;

  const afterTurnOff = gcode.slice(turnOffMatch.index);
  const endstopMatch = afterTurnOff.match(SOFT_ENDSTOP_OFF_RE);
  if (!endstopMatch) return gcode;

  const insertAt = turnOffMatch.index + endstopMatch.index;
  const body = snippet.endsWith('\n') ? snippet : snippet + '\n';
  return gcode.slice(0, insertAt) + body + gcode.slice(insertAt);
}

// Replace everything from the wipe-nozzle START marker (inclusive) up to the
// `M211 R` line (exclusive). The M211 R line is preserved so the softend
// status pop / wipe-nozzle-end section continues cleanly.
function replaceWipeNozzleSection(gcode, replacement) {
  const startMatch = gcode.match(WIPE_NOZZLE_START_RE);
  if (!startMatch) return gcode;

  const afterStart = gcode.slice(startMatch.index);
  const endMatch = afterStart.match(WIPE_NOZZLE_END_RE);
  if (!endMatch) return gcode;

  const endIdx = startMatch.index + endMatch.index;
  const body = replacement.trim();
  return gcode.slice(0, startMatch.index) + body + '\n' + gcode.slice(endIdx);
}

// Replace everything from the START marker (inclusive) up to the END marker
// (exclusive). The END marker — `;========turn off light...` — is preserved
// in the output because it's the header of the next section.
//
// Fallback: if the specific END marker is missing (different firmware /
// custom slicer profile), use the next major `;====+` header instead.
function replaceExtrudeCaliSection(gcode, replacement) {
  const startMatch = gcode.match(EXTRUDE_CALI_START_RE);
  if (!startMatch) return gcode;

  const afterStart = gcode.slice(startMatch.index);

  // Try the specific end marker first
  let endRelIdx = -1;
  const endSpecific = afterStart.match(EXTRUDE_CALI_END_RE);
  if (endSpecific) {
    endRelIdx = endSpecific.index;
  } else {
    // Fallback: skip the start-marker line, then look for the next
    // top-level `;====+` section header.
    const startLineEnd = afterStart.indexOf('\n');
    if (startLineEnd < 0) return gcode;
    const beyondStart = afterStart.slice(startLineEnd);
    const nextSection = beyondStart.match(/\n;====+/);
    if (!nextSection) return gcode;
    endRelIdx = startLineEnd + nextSection.index + 1;
  }

  const endIdx = startMatch.index + endRelIdx;
  const body = replacement.trim();
  return gcode.slice(0, startMatch.index) + body + '\n' + gcode.slice(endIdx);
}

// Replace the LAST occurrence of a line starting with `M18 X Y Z` with a
// plain `M18` (so all steppers, including the extruder, are disabled).
// Anchored on line start to avoid matching the same text inside the
// `; machine_end_gcode = ...` config comment.
function replaceLastM18XYZ(text) {
  const matches = [...text.matchAll(/^M18 X Y Z[^\n]*$/gm)];
  if (matches.length === 0) return text;
  const last = matches[matches.length - 1];
  return text.slice(0, last.index) + 'M18' + text.slice(last.index + last[0].length);
}

// Trim trailing whitespace on every line. Leading indentation is preserved
// (Bambu uses it inside M622/M623 blocks for readability). Done with regex
// rather than split/join to avoid allocating one tiny string per line on
// multi-GB output.
function trimAllLines(text) {
  return text;
    //.replace(/[ \t\r]+\n/g, '\n')   // trailing whitespace on each line
    //.replace(/[ \t\r]+$/, '');      // very last line (no trailing newline)
}

// Split a job's gcode at `M17 R ; restore z current`. `body` includes the
// M17 R line itself; `end` is everything after it (cooldown / park / finish
// sound / motor off — i.e. the printer's machine_end_gcode).
// If the M17 R marker isn't found, returns the whole thing as body.
function splitAtPrintEnd(gcode) {
  const m = gcode.match(PRINT_END_TRIGGER);
  if (!m) return { body: gcode, end: '' };
  const cutoff = m.index + m[0].length;
  return { body: gcode.slice(0, cutoff), end: gcode.slice(cutoff) };
}

// Insert a G-code snippet right AFTER the M73 progress marker whose
// remaining-time `R` (in minutes) is closest to `minutesBeforeEnd`.
// If the total print time is below the trigger window, or if there are no
// M73 markers at all, fall back to injecting at the very start of the gcode.
// Match the progress-marker M73 only (followed by a space) — Bambu also
// emits `M73.2 R1.0 ;Reset left time magnitude` which is a SPEED/TIME RESET
// command with an R unrelated to remaining time.
function injectBeforeEnd(gcode, minutesBeforeEnd, snippet, _ctx) {
  const re = /^M73\s[^\n]*\bR(\d+(?:\.\d+)?)/gm;
  const matches = [];
  let m;
  while ((m = re.exec(gcode)) !== null) {
    matches.push({ index: m.index, remainingMin: parseFloat(m[1]) });
  }

  const body = snippet.endsWith('\n') ? snippet : snippet + '\n';
  const block = `; ==== pre-end trigger (${minutesBeforeEnd} min before end) ====\n${body}`;
  const startBlock = '\n' + block;

  if (matches.length === 0) return startBlock + gcode;

  const totalRemainMin = matches[0].remainingMin;
  if (totalRemainMin <= minutesBeforeEnd) return startBlock + gcode;

  // Pick the M73 whose R is closest to the requested minutes-before-end.
  // Ties go to the earliest match (more conservative: fire slightly early
  // rather than slightly late).
  let bestIdx = 0;
  let bestDist = Math.abs(matches[0].remainingMin - minutesBeforeEnd);
  for (let k = 1; k < matches.length; k++) {
    const d = Math.abs(matches[k].remainingMin - minutesBeforeEnd);
    if (d < bestDist) {
      bestIdx = k;
      bestDist = d;
    }
  }
  const target = matches[bestIdx];

  // Insert right AFTER the chosen M73 line (after its terminating newline).
  const lineEnd = gcode.indexOf('\n', target.index);
  const insertAt = lineEnd >= 0 ? lineEnd + 1 : gcode.length;

  return gcode.slice(0, insertAt) + block + gcode.slice(insertAt);
}

function replaceMetadataValue(xml, key, newValue) {
  const re = new RegExp(
    `(<metadata\\s+key=(["'])${escapeRegex(key)}\\2\\s+value=)(["'])[^"']*(\\3\\s*/?>)`,
    'i'
  );
  if (re.test(xml)) return xml.replace(re, `$1$3${escapeXml(newValue)}$4`);
  return xml;
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function escapeXml(str) {
  return String(str)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

function formatSeconds(totalSeconds) {
  if (!totalSeconds) return '0s';
  const h = Math.floor(totalSeconds / 3600);
  const m = Math.floor((totalSeconds % 3600) / 60);
  const s = totalSeconds % 60;
  const parts = [];
  if (h > 0) parts.push(`${h}h`);
  if (m > 0) parts.push(`${m}m`);
  if (s > 0 || parts.length === 0) parts.push(`${s}s`);
  return parts.join(' ');
}
