// ============================================================================
// Print Queue export worker — does the heavy lifting (gcode concatenation,
// JSZip generation, DEFLATE compression) off the main thread so the UI stays
// responsive on multi-GB farm-loop archives.
//
// Wire protocol:
//   main → worker: { type: 'build', jobs, loops, endGcode, cooldown, baseBuffer }
//   main → worker: { type: 'ack' }                       (backpressure)
//   worker → main: { type: 'progress', message }
//   worker → main: { type: 'chunk', chunk, percent }     (transferable buffer)
//   worker → main: { type: 'done' }
//   worker → main: { type: 'error', message }
// ============================================================================

importScripts('https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js');

// Must mirror constants in printQueue.js
const EXTRUDE_CALI_MARKER = /^;===== extrude cali test =+/gm;
const EXTRUDE_CALI_REPLACEMENT = `

M400
G1 X-48.2 F3000
M400
G0 E50 F100

G1 Z0.2

;M400
;M73 P1.717

G90
M83
G0 E50 F100
M400
`;
const PRINT_END_TRIGGER = /^M17 R[^\n]*\n/m;

// Backpressure: each chunk emitted waits for the main thread to acknowledge
// it has been written to disk before the JSZip stream resumes. Without this,
// chunks pile up in the postMessage queue on big files.
let resumeNext = null;

self.onmessage = (ev) => {
  const msg = ev.data;
  if (msg.type === 'ack') {
    if (resumeNext) {
      const fn = resumeNext;
      resumeNext = null;
      fn();
    }
    return;
  }
  if (msg.type === 'build') {
    handleBuild(msg).catch(err => {
      self.postMessage({ type: 'error', message: err && err.message ? err.message : String(err) });
    });
  }
};

async function handleBuild({ jobs, loops, endGcode, cooldown, baseBuffer, preEndMin, preEndCode }) {
  self.postMessage({ type: 'progress', message: 'Reading base archive...' });

  const baseZip = await JSZip.loadAsync(baseBuffer);
  const filenames = Object.keys(baseZip.files);

  const targetGcodePath = filenames.find(f =>
    f.toLowerCase().endsWith('.gcode') && !f.toLowerCase().endsWith('.md5')
  ) || 'Metadata/plate_1.gcode';

  const ejection = endGcode.endsWith('\n') ? endGcode : endGcode + '\n';
  const ejectionMarker = '\n; ==== farm-loop ejection ====\n';

  self.postMessage({ type: 'progress', message: 'Concatenating G-code...' });

  // Aggregate totals for header + slice_info update
  let totalTime = 0;
  let totalWeight = 0;
  let timeKnown = true;
  let weightKnown = true;
  for (const j of jobs) {
    if (j.timeSeconds != null) totalTime += j.timeSeconds; else timeKnown = false;
    if (j.weightG != null) totalWeight += j.weightG; else weightKnown = false;
  }
  totalTime *= loops;
  totalWeight *= loops;
  const cooldownTotal = (cooldown || 0) * loops;
  if (timeKnown) totalTime += cooldownTotal;

  const chunks = [];
  chunks.push(`; Generated by Print Queue — farm-loop concatenation\n`);
  chunks.push(`; jobs: ${jobs.length}, loops: ${loops}, total prints: ${jobs.length * loops}\n`);
  if (cooldown > 0) {
    chunks.push(`; cooldown after each loop: ${cooldown}s (×${loops} = ${cooldownTotal}s)\n`);
  }
  if (timeKnown) chunks.push(`; total estimated time: ${formatSeconds(totalTime)} (${totalTime}s)\n`);
  if (weightKnown) chunks.push(`; total filament weight [g]: ${totalWeight.toFixed(2)}\n`);
  chunks.push(`;\n`);

  const lastLoopIdx = loops - 1;
  const lastJobIdx = jobs.length - 1;

  for (let loop = 0; loop < loops; loop++) {
    for (let i = 0; i < jobs.length; i++) {
      const job = jobs[i];
      const isVeryLast = loop === lastLoopIdx && i === lastJobIdx;

      let content = replaceExtrudeCaliSection(job.gcodeContent, EXTRUDE_CALI_REPLACEMENT);
      if (preEndCode && preEndMin > 0) {
        content = injectBeforeEnd(content, preEndMin, preEndCode, {
          jobName: job.name,
          loopIdx: loop + 1,
          totalLoops: loops,
          printIdx: i + 1,
          totalPrints: jobs.length,
        });
      }
      if (!isVeryLast) content = stripPrintEnd(content);

      chunks.push(`\n; ==== loop ${loop + 1}/${loops} — print ${i + 1}/${jobs.length}: ${job.name} ====\n`);
      chunks.push(content);
      if (!content.endsWith('\n')) chunks.push('\n');
      chunks.push(ejectionMarker);
      chunks.push(ejection);
    }
  }

  const concatenated = new Blob(chunks, { type: 'text/plain;charset=utf-8' });
  baseZip.file(targetGcodePath, concatenated);

  const md5Path = targetGcodePath + '.md5';
  if (baseZip.files[md5Path]) baseZip.remove(md5Path);

  // Update slice_info.config so the printer shows the correct prediction
  const sliceInfoPath = filenames.find(f => f.toLowerCase().includes('slice_info.config'));
  if (sliceInfoPath) {
    try {
      let xml = await baseZip.files[sliceInfoPath].async('text');
      if (timeKnown) xml = replaceMetadataValue(xml, 'prediction', String(Math.round(totalTime)));
      if (weightKnown) xml = replaceMetadataValue(xml, 'weight', totalWeight.toFixed(2));
      baseZip.file(sliceInfoPath, xml);
    } catch (e) {
      // Non-fatal: keep going
    }
  }

  self.postMessage({ type: 'progress', message: 'Compressing & writing...' });

  // Stream the ZIP back as Uint8Array chunks (transferable).
  await new Promise((resolve, reject) => {
    const stream = baseZip.generateInternalStream({
      type: 'uint8array',
      compression: 'DEFLATE',
      streamFiles: true,
    });
    stream.on('data', (chunk, metadata) => {
      stream.pause();
      const percent = metadata && typeof metadata.percent === 'number' ? metadata.percent : 0;
      // IMPORTANT: pako (JSZip's DEFLATE engine) reuses one internal ArrayBuffer
      // across chunks, exposing each chunk as a different Uint8Array view onto it.
      // If we transfer chunk.buffer, the next chunk pako emits points to a
      // detached buffer → "Cannot perform Construct on a detached ArrayBuffer".
      // Copy into a fresh buffer before transferring.
      const copy = new Uint8Array(chunk);
      self.postMessage(
        { type: 'chunk', chunk: copy, percent },
        [copy.buffer]
      );
      resumeNext = () => stream.resume();
    });
    stream.on('error', err => reject(err));
    stream.on('end', () => resolve());
    stream.resume();
  });

  self.postMessage({ type: 'done' });
}

// ── Transformations (mirrors of main thread) ───────────────────────────────
function replaceExtrudeCaliSection(gcode, replacement) {
  const matches = [];
  let m;
  EXTRUDE_CALI_MARKER.lastIndex = 0;
  while ((m = EXTRUDE_CALI_MARKER.exec(gcode)) !== null) {
    matches.push({ index: m.index, end: m.index + m[0].length });
  }
  const body = replacement.trim();
  if (matches.length >= 2) {
    const a = matches[0], b = matches[1];
    return gcode.slice(0, a.end) + '\n' + body + '\n' + gcode.slice(b.index);
  }
  if (matches.length === 1) {
    const a = matches[0];
    const after = gcode.slice(a.end);
    const nextSection = after.match(/\n;====+/);
    if (nextSection) {
      const endIdx = a.end + nextSection.index + 1;
      return gcode.slice(0, a.end) + '\n' + body + '\n' + gcode.slice(endIdx);
    }
  }
  return gcode;
}

function stripPrintEnd(gcode) {
  const m = gcode.match(PRINT_END_TRIGGER);
  if (!m) return gcode;
  return gcode.slice(0, m.index + m[0].length);
}

// Insert a G-code snippet `secondsBeforeEnd` seconds before the end of the
// print. Uses Bambu/Marlin `M73 P<percent> R<minutes>` progress markers to
// locate the insertion point. If the print is shorter than `secondsBeforeEnd`
// (or has no M73 markers), inserts at the very start of the gcode.
//
// The first M73 in the file has the largest R value (≈ total print time);
// each subsequent M73 has a smaller R. We pick the first M73 whose remaining
// time (R × 60) falls below the threshold — that's the entry into the
// "last N seconds" zone.
// Insert a G-code snippet right AFTER the M73 progress marker whose
// remaining-time `R` (in minutes) is closest to `minutesBeforeEnd`.
// If the total print time is below the trigger window, or if there are no
// M73 markers at all, fall back to injecting at the very start of the gcode.
function injectBeforeEnd(gcode, minutesBeforeEnd, snippet, ctx) {
  // Match the progress-marker M73 only (followed by a space).
  // The Bambu firmware also emits `M73.2 R1.0 ;Reset left time magnitude`
  // which is a SPEED/TIME RESET command — its R value is unrelated to
  // remaining time and would skew the "closest" match.
  const re = /^M73\s[^\n]*\bR(\d+(?:\.\d+)?)/gm;
  const matches = [];
  let m;
  while ((m = re.exec(gcode)) !== null) {
    matches.push({ index: m.index, line: m[0], remainingMin: parseFloat(m[1]) });
  }

  const body = snippet.endsWith('\n') ? snippet : snippet + '\n';
  const block = `; ==== pre-end trigger (${minutesBeforeEnd} min before end) ====\n${body}`;
  const startBlock = '\n' + block;
  const tag = ctx
    ? `[pre-end ${ctx.loopIdx}/${ctx.totalLoops}·${ctx.printIdx}/${ctx.totalPrints} ${ctx.jobName}]`
    : '[pre-end]';

  if (matches.length === 0) {
    console.log(`${tag} no M73 R markers found in gcode → injecting at the very start`);
    return startBlock + gcode;
  }

  const totalRemainMin = matches[0].remainingMin;
  const lastM73 = matches[matches.length - 1];

  console.log(
    `${tag} found ${matches.length} M73 markers. ` +
    `Total print duration ≈ ${totalRemainMin} min. ` +
    `First: "${matches[0].line}"  ·  Last: "${lastM73.line}"`
  );

  if (totalRemainMin <= minutesBeforeEnd) {
    console.log(
      `${tag} print is shorter than the trigger window ` +
      `(${totalRemainMin} min ≤ ${minutesBeforeEnd} min) → injecting at the very start`
    );
    return startBlock + gcode;
  }

  // Pick the M73 whose R is closest to the requested minutes-before-end.
  // Ties go to the earliest match (more conservative: fire slightly early
  // rather than slightly late).
  let bestIdx = 0;
  let bestDist = Math.abs(matches[0].remainingMin - minutesBeforeEnd);
  for (let k = 1; k < matches.length; k++) {
    const d = Math.abs(matches[k].remainingMin - minutesBeforeEnd);
    if (d < bestDist) {
      bestIdx = k;
      bestDist = d;
    }
  }
  const target = matches[bestIdx];

  // Insert right AFTER the chosen M73 line (after its terminating newline).
  const lineEnd = gcode.indexOf('\n', target.index);
  const insertAt = lineEnd >= 0 ? lineEnd + 1 : gcode.length;

  console.log(
    `${tag} injecting after marker #${bestIdx + 1}/${matches.length}: ` +
    `"${target.line}" (R = ${target.remainingMin} min, |R − ${minutesBeforeEnd}| = ${bestDist})`
  );

  return gcode.slice(0, insertAt) + block + gcode.slice(insertAt);
}

function replaceMetadataValue(xml, key, newValue) {
  const re = new RegExp(
    `(<metadata\\s+key=(["'])${escapeRegex(key)}\\2\\s+value=)(["'])[^"']*(\\3\\s*/?>)`,
    'i'
  );
  if (re.test(xml)) return xml.replace(re, `$1$3${escapeXml(newValue)}$4`);
  return xml;
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function escapeXml(str) {
  return String(str)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

function formatSeconds(totalSeconds) {
  if (!totalSeconds) return '0s';
  const h = Math.floor(totalSeconds / 3600);
  const m = Math.floor((totalSeconds % 3600) / 60);
  const s = totalSeconds % 60;
  const parts = [];
  if (h > 0) parts.push(`${h}h`);
  if (m > 0) parts.push(`${m}m`);
  if (s > 0 || parts.length === 0) parts.push(`${s}s`);
  return parts.join(' ');
}
